id: P008178
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 13:06:17.592976
source_metadata:
  id: bdr:W20381
  title: མཚོ་ལྷོ་བོད་རིགས་རང་སྐྱོང་ཁུལ་གྱི་ལོ་རྒྱུས་ཆེ་ལོང་ཙམ་བརྗོད་པ་སྙན་དབང་གསོ་བའི་ཅོང་སྒྲ
  author: ''
  volumes:
    ea689f503a7b430f9a756d3ca338a062:
      image_group_id: I1GS105587
      title: ''
      volume_number: 1
      total_pages: 314
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
